%% script for concise IC tecplot output
clc; clear;
src_dirname = [...
    'C:\Users\Will\Documents\MATLAB\VT_Research',...
    '\unsteady-ete-1D-burgers\',...
    '\post_processing\'];
src_fname = 'ETE-IC-BD-4_pulseplus_testnewBC_long';
% src_fname = 'ETE-IC-BD-4_pulseplus_test';
% src_dirname = [...
%     'C:\Users\Will\Documents\MATLAB\VT_Research',...
%     '\unsteady_iterative_correction_results',...
%     '\iterative_weighting_experiments\'];
% src_fname = 'ETE-IC-BD-4_alg1_lin-weights2';
% src_fname = 'ETE-IC-BD-4_alg1_inv-weights1';
% src_fname = 'ETE-IC-BD-4_alg1_s2-weights1';
% src_fname = 'ETE-IC-BD-4_alg1_no-weights';

% target_dirname = [...
%     'C:\Users\Will\Documents\MATLAB\VT_Research',...
%     '\unsteady_iterative_correction_results',...
%     '\iterative_weighting_experiments',...
%     '\tecplot_output\'];
target_dirname = [...
    'C:\Users\Will\Documents\MATLAB\VT_Research',...
    '\unsteady_iterative_correction_results',...
    '\pulse-decay',...
    '\tecplot_output\'];
% [SE1,SE2,PE1,PE2,DEBUG] = parse_IC_OOA_concise([src_dirname,src_fname]);
[SE,PE,DEBUG] = parse_IC_OOA_concise_time([src_dirname,src_fname]);
format_for_tecplot(target_dirname,[src_fname,'L1_time_Error.dat'],SE.L(1));
% format_for_tecplot(target_dirname,[src_fname,'L1_Error.dat'],SE1.L(1));
% format_for_tecplot(target_dirname,[src_fname,'L1_OOA.dat'],PE1.L(1));

% format_for_tecplot(target_dirname,['time_',src_fname,'L1_OOA.dat'],PE2.L(1));